/* ===== cards.js — Open-source CAH card deck ===== */
/* Sourced from json-against-humanity (CC BY-NC-SA 2.0) */

const CAH_BLACK_CARDS = [
  { text: "What's the most useless superpower?", pick: 1 },
  { text: "I never leave home without ___.", pick: 1 },
  { text: "What's the secret ingredient in my grandma's cookies?", pick: 1 },
  { text: "During sex, I like to think about ___.", pick: 1 },
  { text: "What's that smell?", pick: 1 },
  { text: "___ is a slippery slope that leads to ___.", pick: 2 },
  { text: "After the earthquake, the survivors were forced to resort to ___.", pick: 1 },
  { text: "What's Batman's guilty pleasure?", pick: 1 },
  { text: "Maybe she's born with it. Maybe it's ___.", pick: 1 },
  { text: "Introducing the world's first all-___ restaurant!", pick: 1 },
  { text: "Scientists have discovered a shocking new element: ___.", pick: 1 },
  { text: "What's that sound?", pick: 1 },
  { text: "Life was hard on the frontier. We had to survive on nothing but ___ and ___.", pick: 2 },
  { text: "What's my anti-drug?", pick: 1 },
  { text: "Step 1: ___. Step 2: ___. Step 3: Profit!", pick: 2 },
  { text: "In a pinch, ___ can be used as a contraceptive.", pick: 1 },
  { text: "What did the Buddhist attain through pure meditation?", pick: 1 },
  { text: "This is your captain speaking. Please fasten your seatbelts. We're flying through ___.", pick: 1 },
  { text: "Why do I always feel so sticky?", pick: 1 },
  { text: "MTV's new reality show features eight ___ living in a house together.", pick: 1 },
  { text: "War! What is it good for?", pick: 1 },
  { text: "A tragic accident has left me unable to feel anything but ___.", pick: 1 },
  { text: "In a shocking turn of events, the pope has converted to ___.", pick: 1 },
  { text: "I get by with a little help from ___.", pick: 1 },
  { text: "Doctors recommend drinking eight glasses of ___ a day.", pick: 1 },
  { text: "Next on ESPN2, the World Series of ___.", pick: 1 },
  { text: "What's the most metal name for a band?", pick: 1 },
  { text: "My New Year's resolution is to lose weight with the help of ___.", pick: 1 },
  { text: "This is the worst birthday ever. You didn't get me ___ at all?", pick: 1 },
  { text: "How did I lose my virginity?", pick: 1 },
  { text: "I'm sorry professor, I can't come to class today because of ___.", pick: 1 },
  { text: "Our love is like ___.", pick: 1 },
  { text: "The academy award for ___ goes to ___.", pick: 2 },
  { text: "What's the most disappointing gift a child could receive?", pick: 1 },
  { text: "I got 99 problems but ___ ain't one.", pick: 1 },
  { text: "Why am I sticky?", pick: 1 },
  { text: "Old MacDonald had a farm, and on that farm there was ___.", pick: 1 },
  { text: "What is the gift that keeps on giving?", pick: 1 },
  { text: "Alternative medicine is now embracing the healing power of ___.", pick: 1 },
  { text: "What will always get you out of a speeding ticket?", pick: 1 },
  { text: "TSA guidelines now prohibit ___ on all flights.", pick: 1 },
  { text: "What is George W. Bush thinking about right now?", pick: 1 },
  { text: "How am I maintaining my figure?", pick: 1 },
  { text: "I'm throwing a dinner party for ___.", pick: 1 },
  { text: "Studies show that the average American spends 14 minutes a day thinking about ___.", pick: 1 },
  { text: "What has been making life difficult at the nudist colony?", pick: 1 },
  { text: "What is the leading cause of death in the United States?", pick: 1 },
  { text: "In the year 2100, ___% of all humans will be living underground.", pick: 1 },
  { text: "A new study shows that ___ is the cause of most car accidents.", pick: 1 },
  { text: "Before I kill you, Mr. Bond, I must show you ___.", pick: 1 },
];

const CAH_WHITE_CARDS = [
  "Nicolas Cage",
  "Unexpected Hitler",
  "Praying the gay away",
  "Explosive diarrhea",
  "A tiny horse",
  "An erection that lasts more than 4 hours",
  "Fingering",
  "A sassy black woman",
  "Jibber-jabber",
  "The taint; the grundle; the fleshy fun-bridge",
  "Pretending to care",
  "Racial profiling",
  "Being on fire",
  "Hope",
  "The violation of our most basic human rights",
  "Launching a glitter-bomb into a crowd of unsuspecting children",
  "Getting so angry you pop a blood vessel in your eye",
  "Flying robots that kill people",
  "Sunshine and rainbows",
  "Making the penises kiss",
  "The feeling of knowing you've finally done something right",
  "Swiftly achieving orgasm",
  "Poorly-timed Holocaust jokes",
  "A poorly-timed death in the family",
  "Child beauty pageants",
  "Vigorous jazz hands",
  "Eating the last known bison",
  "Genghis Khan",
  "Lactation",
  "A really good lawyer",
  "White privilege",
  "The systematic destruction of indigenous peoples",
  "Charisma, uniqueness, nerve, and talent",
  "Literally eating shit",
  "A lifetime of sadness",
  "The miracle of childbirth",
  "Getting drunk on mouthwash",
  "Taking off your shirt",
  "The heart of a child",
  "Farting and walking away",
  "Asking too many questions about my bowel movements",
  "Dry heaving",
  "One trillion dollars",
  "The token minority",
  "Surprise sex",
  "Puppies!",
  "Passing a kidney stone",
  "A stray pube",
  "Bees?",
  "A magic trick that really works",
  "Inappropriate yodeling",
  "Assless chaps",
  "A disappointing birthday party",
  "Making a half-hearted apology",
  "Not giving a shit about the Third World",
  "Seppuku",
  "Morgan Freeman's voice",
  "Wearing a too-small top hat",
  "Roofies",
  "Spontaneous human combustion",
  "The placenta",
  "Eating all of the ice cream before the kids get home",
  "Amputees",
  "The entire Internet",
  "Another disappointing NFL season",
  "Sean Connery",
  "The Jews",
  "A windmill full of corpses",
  "Auschwitz",
  "Passive-aggressive Post-it notes",
  "An erection",
  "A balanced breakfast",
  "Getting blackout drunk with Warren Buffett",
  "Dying alone",
  "Fiery poops",
  "Handcuffs",
  "Republicans",
  "The clitoris",
  "Profound self-loathing",
  "Licking things to claim them as your own",
  "Two midgets shitting into a bucket",
  "Exquisite knowledge of wine",
  "Poorly-conceived tattoos",
  "Cuddling",
  "The invisible hand",
  "The three-fifths compromise",
  "Horse-sized ducks",
  "A falcon with a cap on",
  "Panicking",
  "Grandma",
  "The force",
  "Dick Cheney",
  "Smegma",
  "Actual witches",
  "Coming out of the closet as a brony",
  "A freshly-vacuumed carpet",
  "Justin Bieber",
  "Extreme couponing",
  "Inappropriate touching at the airport",
  "The inevitable heat death of the universe",
  "Being on the wrong side of history",
];

const WINNER_PRAISES = [
  "🎉 Absolute magnificence! You're the most gloriously depraved person in the room!",
  "👑 Bow down, peasants! A true connoisseur of terrible taste has emerged!",
  "🔥 That answer was so wrong it looped back around to being right.",
  "😈 Somewhere, an angel just lost its wings because of that answer.",
  "🏆 History will remember you — mostly with deep, deep shame.",
  "🍾 Pop the champagne! The most morally flexible player has won the round!",
  "🌟 You answered that like you've been to therapy… and then immediately stopped going.",
  "🎭 Your parents are so proud. So deeply confused, but so proud.",
  "💀 That was so dark even the void flinched.",
  "😂 You may have no soul, but you definitely have the most points!",
  "🧠 Pure genius. Despicable, shameful genius.",
  "🦹 Not all heroes wear capes. Some just play spectacularly awful cards.",
];
